ARDUINO_PORT = /dev/ttyUSB0
BOARD_TAG = uno
ARDUINO_LIBS = SoftwareSerial Wire makeblock
ARDUINO_DIR = /opt/arduino
#USER_LIB_PATH = $(ARDUINO_DIR)/libraries/makeblock

include Arduino-Makefile/Arduino.mk
